---
dependency:
  name: galaxy

driver:
  name: docker

role_name_check: 2

platforms:
  - name: ansible_role_helm_opensuse
    image: opensuse/leap:15.5

provisioner:
  name: ansible
  playbooks:
    converge: ../default/converge.yml

verifier:
  name: testinfra
  directory: ../default/tests
