---
dependency:
  name: galaxy

driver:
  name: docker

role_name_check: 2

platforms:
  - name: ansible_role_helm_ubuntu_min
    image: ubuntu:18.04

provisioner:
  name: ansible
  playbooks:
    converge: ../default/converge.yml

scenario:
  name: ubuntu_min

verifier:
  name: testinfra
  directory: ../default/tests
