---
dependency:
  name: galaxy

driver:
  name: docker

role_name_check: 2

platforms:
  - name: ansible_role_helm_debian_max
    image: debian:11

provisioner:
  name: ansible
  playbooks:
    converge: ../default/converge.yml

scenario:
  name: debian_max

verifier:
  name: testinfra
  directory: ../default/tests
